- hosts: all
  tasks:
    - name: Create a network for the container
      docker_network:
        name: apache_network
        ipam_config:
          - subnet: 172.168.10.0/30

    - name: Pull a Docker Image
      docker_image:
        name: httpd
        tag: latest
        source: pull
      register: z

    - name: Checking Pull Status
      debug:
        var: z

    - name: Creating a Persistent Volume Dir
      file:
        path: "/root/pv"
        state: directory

    - name: Copying the HTML code in the Directory
      copy:
        src: "/root/veer/index.html"
        dest: "/root/pv/"

    - name: Launching an HTTPD Container
      when: z.failed == false
      docker_container:
        name: apache-server
        image: httpd
        state: started
        exposed_ports:
          - "80"
        ports:
          - "8888:80"
        volumes:
          - "/root/pv:/usr/local/apache2/htdocs"
        networks:
          - name: apache_network

